version: '3'
services:
  postgresdb:
    image: postgres:latest
    container_name: postgresdb
    expose:
      - '5432'
    environment:
      POSTGRES_USER: 'npm'
      POSTGRES_PASSWORD: 'Cyb3rZ0ne$;'
      POSTGRES_DB: 'npm'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - npm_network
  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
        #- '8081:81'
    environment:
      DB_POSTGRES_HOST: 'postgresdb'
      DB_POSTGRES_PORT: '5432'
      DB_POSTGRES_USER: 'npm'
      DB_POSTGRES_PASSWORD: 'Cyb3rZ0ne$;'
      DB_POSTGRES_NAME: 'npm'
    volumes:
      - ./npm_data:/data
      - ./npm_letsencrypt:/etc/letsencrypt
    networks:
      -  npm_network

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    expose:
      - 3306
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ;AOlSR8hzu12
      
    volumes:
      - ./mariadb_data:/var/lib/mysql
    networks:
      - npm_network
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    expose:
      - 80
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    depends_on:
      - mariadb
    networks:
      - npm_network

  hesk:
    container_name: hesk
    image: brunoah/hesk
    volumes:
      - ./hesk:/var/www/html
    expose:
      - 80
    networks:
      - npm_network
    depends_on:
      - mariadb

volumes:
  postgres_data:
    driver: local
  npm_data:
    driver: local
  npm_letsencrypt:
    driver: local
  mariadb_data:
    driver: local
  hesk:
    driver: local
networks:
  npm_network:
    driver: bridge
